name: Setup Playwright Chromium
description: Cache and install Playwright Chromium browser + OS dependencies

runs:
  using: composite
  steps:
    - name: Get Playwright version
      shell: bash
      run: |
        echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('./package-lock.json').packages['node_modules/playwright'].version)")" >> $GITHUB_ENV

    - name: Cache Playwright Chromium
      uses: actions/cache@v4
      id: playwright-cache
      with:
        path: ~/.cache/ms-playwright
        key: playwright-chromium-${{ runner.os }}-${{ env.PLAYWRIGHT_VERSION }}

    - name: Install Playwright Chromium
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      shell: bash
      run: npx playwright install --with-deps chromium

    - name: Install Playwright OS dependencies
      if: steps.playwright-cache.outputs.cache-hit == 'true'
      shell: bash
      run: npx playwright install-deps chromium
